name: 🐰 Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: 🏭 Build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🐑 Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: 🏗️ Lint
        uses: golangci/golangci-lint-action@v3

      - name: 🧪 Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: 📊 Coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out
          flags: unittests
          name: codecov-umbrella
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 📦 Build
        run: go build -o ./bin/ cmd/main.go
